// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using eVote360.Infrastructure.Persistence;

#nullable disable

namespace eVote360.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260115185950_ReseedBaseAnd2024")]
    partial class ReseedBaseAnd2024
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.11");

            modelBuilder.Entity("eVote360.Domain.Entities.Candidatura", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("EleccionId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("FotoPath")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<string>("NombreBoleta")
                        .HasColumnType("TEXT");

                    b.Property<string>("NombreCompleto")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("PartidoPoliticoId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("PuestoElectivoId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("PartidoPoliticoId");

                    b.HasIndex("PuestoElectivoId");

                    b.HasIndex("EleccionId", "PuestoElectivoId", "PartidoPoliticoId")
                        .IsUnique();

                    b.ToTable("Candidaturas");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            EleccionId = 1,
                            IsActive = true,
                            NombreBoleta = "Luis Abinader",
                            NombreCompleto = "Luis Abinader",
                            PartidoPoliticoId = 1,
                            PuestoElectivoId = 1
                        },
                        new
                        {
                            Id = 2,
                            EleccionId = 1,
                            IsActive = true,
                            NombreBoleta = "Raquel Peña",
                            NombreCompleto = "Raquel Peña",
                            PartidoPoliticoId = 1,
                            PuestoElectivoId = 5
                        },
                        new
                        {
                            Id = 3,
                            EleccionId = 1,
                            IsActive = true,
                            NombreBoleta = "Abel Martínez",
                            NombreCompleto = "Abel Martínez",
                            PartidoPoliticoId = 2,
                            PuestoElectivoId = 1
                        },
                        new
                        {
                            Id = 4,
                            EleccionId = 1,
                            IsActive = true,
                            NombreBoleta = "Zoraima Cuello",
                            NombreCompleto = "Zoraima Cuello",
                            PartidoPoliticoId = 2,
                            PuestoElectivoId = 5
                        },
                        new
                        {
                            Id = 5,
                            EleccionId = 1,
                            IsActive = true,
                            NombreBoleta = "Leonel Fernández",
                            NombreCompleto = "Leonel Fernández",
                            PartidoPoliticoId = 3,
                            PuestoElectivoId = 1
                        },
                        new
                        {
                            Id = 6,
                            EleccionId = 1,
                            IsActive = true,
                            NombreBoleta = "Ingrid Mendoza",
                            NombreCompleto = "Ingrid Mendoza",
                            PartidoPoliticoId = 3,
                            PuestoElectivoId = 5
                        });
                });

            modelBuilder.Entity("eVote360.Domain.Entities.Eleccion", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("Anio")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("Fecha")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Elecciones");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Anio = 2024,
                            Fecha = new DateTime(2024, 5, 19, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsActive = true,
                            Tipo = "Presidenciales y Congresuales"
                        });
                });

            modelBuilder.Entity("eVote360.Domain.Entities.PartidoPolitico", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Descripcion")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<string>("LogoPath")
                        .HasColumnType("TEXT");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Siglas")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("PartidosPoliticos");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Descripcion = "Partido político (RD)",
                            IsActive = true,
                            Nombre = "Partido Revolucionario Moderno",
                            Siglas = "PRM"
                        },
                        new
                        {
                            Id = 2,
                            Descripcion = "Partido político (RD)",
                            IsActive = true,
                            Nombre = "Partido de la Liberación Dominicana",
                            Siglas = "PLD"
                        },
                        new
                        {
                            Id = 3,
                            Descripcion = "Partido político (RD)",
                            IsActive = true,
                            Nombre = "Fuerza del Pueblo",
                            Siglas = "FP"
                        },
                        new
                        {
                            Id = 4,
                            Descripcion = "Partido político (RD)",
                            IsActive = true,
                            Nombre = "Partido Revolucionario Dominicano",
                            Siglas = "PRD"
                        });
                });

            modelBuilder.Entity("eVote360.Domain.Entities.PuestoElectivo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Descripcion")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("PuestosElectivos");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Descripcion = "Puesto electivo nacional",
                            IsActive = true,
                            Nombre = "Presidencia"
                        },
                        new
                        {
                            Id = 2,
                            Descripcion = "Representación provincial",
                            IsActive = true,
                            Nombre = "Senaduría"
                        },
                        new
                        {
                            Id = 3,
                            Descripcion = "Cámara de Diputados",
                            IsActive = true,
                            Nombre = "Diputación"
                        },
                        new
                        {
                            Id = 4,
                            Descripcion = "Gobierno municipal",
                            IsActive = true,
                            Nombre = "Alcaldía"
                        },
                        new
                        {
                            Id = 5,
                            Descripcion = "Puesto nacional (acompaña candidatura presidencial)",
                            IsActive = true,
                            Nombre = "Vicepresidencia"
                        },
                        new
                        {
                            Id = 6,
                            Descripcion = "Puesto municipal (acompaña candidatura a alcaldía)",
                            IsActive = true,
                            Nombre = "Vicealcaldía"
                        },
                        new
                        {
                            Id = 7,
                            Descripcion = "Concejo municipal (regidores/as)",
                            IsActive = true,
                            Nombre = "Regiduría"
                        },
                        new
                        {
                            Id = 8,
                            Descripcion = "Director/a de Distrito Municipal",
                            IsActive = true,
                            Nombre = "Dirección Distrito Municipal"
                        },
                        new
                        {
                            Id = 9,
                            Descripcion = "Subdirector/a de Distrito Municipal",
                            IsActive = true,
                            Nombre = "Subdirección Distrito Municipal"
                        },
                        new
                        {
                            Id = 10,
                            Descripcion = "Vocales del Distrito Municipal",
                            IsActive = true,
                            Nombre = "Vocalía Distrito Municipal"
                        },
                        new
                        {
                            Id = 11,
                            Descripcion = "Representación ante el Parlamento Centroamericano (PARLACEN)",
                            IsActive = true,
                            Nombre = "Diputación PARLACEN"
                        });
                });

            modelBuilder.Entity("eVote360.Domain.Entities.Voto", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("CandidaturaId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("EleccionId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("FechaHora")
                        .HasColumnType("TEXT");

                    b.Property<int>("PuestoElectivoId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("TokenVoto")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("CandidaturaId");

                    b.HasIndex("PuestoElectivoId");

                    b.HasIndex("EleccionId", "PuestoElectivoId");

                    b.ToTable("Votos");
                });

            modelBuilder.Entity("eVote360.Domain.Entities.Candidatura", b =>
                {
                    b.HasOne("eVote360.Domain.Entities.Eleccion", "Eleccion")
                        .WithMany("Candidaturas")
                        .HasForeignKey("EleccionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("eVote360.Domain.Entities.PartidoPolitico", "PartidoPolitico")
                        .WithMany()
                        .HasForeignKey("PartidoPoliticoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("eVote360.Domain.Entities.PuestoElectivo", "PuestoElectivo")
                        .WithMany()
                        .HasForeignKey("PuestoElectivoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Eleccion");

                    b.Navigation("PartidoPolitico");

                    b.Navigation("PuestoElectivo");
                });

            modelBuilder.Entity("eVote360.Domain.Entities.Voto", b =>
                {
                    b.HasOne("eVote360.Domain.Entities.Candidatura", "Candidatura")
                        .WithMany("Votos")
                        .HasForeignKey("CandidaturaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("eVote360.Domain.Entities.Eleccion", "Eleccion")
                        .WithMany("Votos")
                        .HasForeignKey("EleccionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("eVote360.Domain.Entities.PuestoElectivo", "PuestoElectivo")
                        .WithMany()
                        .HasForeignKey("PuestoElectivoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Candidatura");

                    b.Navigation("Eleccion");

                    b.Navigation("PuestoElectivo");
                });

            modelBuilder.Entity("eVote360.Domain.Entities.Candidatura", b =>
                {
                    b.Navigation("Votos");
                });

            modelBuilder.Entity("eVote360.Domain.Entities.Eleccion", b =>
                {
                    b.Navigation("Candidaturas");

                    b.Navigation("Votos");
                });
#pragma warning restore 612, 618
        }
    }
}
