// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using eVote360.Infrastructure.Persistence;

#nullable disable

namespace eVote360.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260115144228_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.11");

            modelBuilder.Entity("eVote360.Domain.Entities.PartidoPolitico", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Descripcion")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<string>("LogoPath")
                        .HasColumnType("TEXT");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("TEXT");

                    b.Property<string>("Siglas")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("PartidosPoliticos");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Descripcion = "Partido de gobierno y mayoritario",
                            IsActive = true,
                            Nombre = "Partido Revolucionario Moderno",
                            Siglas = "PRM"
                        },
                        new
                        {
                            Id = 2,
                            Descripcion = "Fuerza histórica de oposición",
                            IsActive = true,
                            Nombre = "Partido de la Liberación Dominicana",
                            Siglas = "PLD"
                        },
                        new
                        {
                            Id = 3,
                            Descripcion = "Partido emergente con crecimiento significativo",
                            IsActive = true,
                            Nombre = "Fuerza del Pueblo",
                            Siglas = "FP"
                        },
                        new
                        {
                            Id = 4,
                            Descripcion = "Estructura tradicional con reconocimiento",
                            IsActive = true,
                            Nombre = "Partido Revolucionario Dominicano",
                            Siglas = "PRD"
                        });
                });

            modelBuilder.Entity("eVote360.Domain.Entities.PuestoElectivo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Descripcion")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("PuestosElectivos");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Descripcion = "Puesto electivo nacional",
                            IsActive = true,
                            Nombre = "Presidencia"
                        },
                        new
                        {
                            Id = 2,
                            Descripcion = "Representación provincial",
                            IsActive = true,
                            Nombre = "Senaduría"
                        },
                        new
                        {
                            Id = 3,
                            Descripcion = "Cámara de Diputados",
                            IsActive = true,
                            Nombre = "Diputación"
                        },
                        new
                        {
                            Id = 4,
                            Descripcion = "Gobierno municipal",
                            IsActive = true,
                            Nombre = "Alcaldía"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
