// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using eVote360.Infrastructure.Persistence;

#nullable disable

namespace eVote360.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260115162717_SeedMorePuestosElectivos")]
    partial class SeedMorePuestosElectivos
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.11");

            modelBuilder.Entity("eVote360.Domain.Entities.PartidoPolitico", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Descripcion")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<string>("LogoPath")
                        .HasColumnType("TEXT");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Siglas")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("PartidosPoliticos", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Descripcion = "Partido de gobierno y mayoritario",
                            IsActive = true,
                            Nombre = "Partido Revolucionario Moderno",
                            Siglas = "PRM"
                        },
                        new
                        {
                            Id = 2,
                            Descripcion = "Fuerza histórica de oposición",
                            IsActive = true,
                            Nombre = "Partido de la Liberación Dominicana",
                            Siglas = "PLD"
                        },
                        new
                        {
                            Id = 3,
                            Descripcion = "Partido emergente con crecimiento significativo",
                            IsActive = true,
                            Nombre = "Fuerza del Pueblo",
                            Siglas = "FP"
                        },
                        new
                        {
                            Id = 4,
                            Descripcion = "Estructura tradicional con reconocimiento",
                            IsActive = true,
                            Nombre = "Partido Revolucionario Dominicano",
                            Siglas = "PRD"
                        });
                });

            modelBuilder.Entity("eVote360.Domain.Entities.PuestoElectivo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Descripcion")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("PuestosElectivos", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Descripcion = "Puesto electivo nacional",
                            IsActive = true,
                            Nombre = "Presidencia"
                        },
                        new
                        {
                            Id = 2,
                            Descripcion = "Representación provincial",
                            IsActive = true,
                            Nombre = "Senaduría"
                        },
                        new
                        {
                            Id = 3,
                            Descripcion = "Cámara de Diputados",
                            IsActive = true,
                            Nombre = "Diputación"
                        },
                        new
                        {
                            Id = 4,
                            Descripcion = "Gobierno municipal",
                            IsActive = true,
                            Nombre = "Alcaldía"
                        },
                        new
                        {
                            Id = 5,
                            Descripcion = "Puesto nacional (acompaña candidatura presidencial)",
                            IsActive = true,
                            Nombre = "Vicepresidencia"
                        },
                        new
                        {
                            Id = 6,
                            Descripcion = "Puesto municipal (acompaña candidatura a alcaldía)",
                            IsActive = true,
                            Nombre = "Vicealcaldía"
                        },
                        new
                        {
                            Id = 7,
                            Descripcion = "Concejo municipal (regidores/as)",
                            IsActive = true,
                            Nombre = "Regiduría"
                        },
                        new
                        {
                            Id = 8,
                            Descripcion = "Director/a de Distrito Municipal",
                            IsActive = true,
                            Nombre = "Dirección Distrito Municipal"
                        },
                        new
                        {
                            Id = 9,
                            Descripcion = "Subdirector/a de Distrito Municipal",
                            IsActive = true,
                            Nombre = "Subdirección Distrito Municipal"
                        },
                        new
                        {
                            Id = 10,
                            Descripcion = "Vocales del Distrito Municipal",
                            IsActive = true,
                            Nombre = "Vocalía Distrito Municipal"
                        },
                        new
                        {
                            Id = 11,
                            Descripcion = "Representación ante el Parlamento Centroamericano (PARLACEN)",
                            IsActive = true,
                            Nombre = "Diputación PARLACEN"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
