// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using eVote360.Infrastructure.Persistence;

#nullable disable

namespace eVote360.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.11");

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ClaimType")
                        .HasColumnType("TEXT");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("TEXT");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ClaimType")
                        .HasColumnType("TEXT");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("TEXT");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("TEXT");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("TEXT");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("TEXT");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("TEXT");

                    b.Property<string>("RoleId")
                        .HasColumnType("TEXT");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("TEXT");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.Property<string>("Value")
                        .HasColumnType("TEXT");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("eVote360.Domain.Entities.AppUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("INTEGER");

                    b.Property<string>("FullName")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("TEXT");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("TEXT");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("TEXT");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("TEXT");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("INTEGER");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("eVote360.Domain.Entities.Candidatura", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("EleccionId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("FotoPath")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<string>("NombreBoleta")
                        .HasColumnType("TEXT");

                    b.Property<string>("NombreCompleto")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("PartidoPoliticoId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("PuestoElectivoId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("PartidoPoliticoId");

                    b.HasIndex("PuestoElectivoId");

                    b.HasIndex("EleccionId", "PuestoElectivoId", "PartidoPoliticoId")
                        .IsUnique();

                    b.ToTable("Candidaturas");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            EleccionId = 1,
                            IsActive = true,
                            NombreBoleta = "Luis Abinader",
                            NombreCompleto = "Luis Abinader",
                            PartidoPoliticoId = 1,
                            PuestoElectivoId = 1
                        },
                        new
                        {
                            Id = 2,
                            EleccionId = 1,
                            IsActive = true,
                            NombreBoleta = "Raquel Peña",
                            NombreCompleto = "Raquel Peña",
                            PartidoPoliticoId = 1,
                            PuestoElectivoId = 5
                        },
                        new
                        {
                            Id = 3,
                            EleccionId = 1,
                            IsActive = true,
                            NombreBoleta = "Abel Martínez",
                            NombreCompleto = "Abel Martínez",
                            PartidoPoliticoId = 2,
                            PuestoElectivoId = 1
                        },
                        new
                        {
                            Id = 4,
                            EleccionId = 1,
                            IsActive = true,
                            NombreBoleta = "Zoraima Cuello",
                            NombreCompleto = "Zoraima Cuello",
                            PartidoPoliticoId = 2,
                            PuestoElectivoId = 5
                        },
                        new
                        {
                            Id = 5,
                            EleccionId = 1,
                            IsActive = true,
                            NombreBoleta = "Leonel Fernández",
                            NombreCompleto = "Leonel Fernández",
                            PartidoPoliticoId = 3,
                            PuestoElectivoId = 1
                        },
                        new
                        {
                            Id = 6,
                            EleccionId = 1,
                            IsActive = true,
                            NombreBoleta = "Ingrid Mendoza",
                            NombreCompleto = "Ingrid Mendoza",
                            PartidoPoliticoId = 3,
                            PuestoElectivoId = 5
                        });
                });

            modelBuilder.Entity("eVote360.Domain.Entities.Eleccion", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("Anio")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("Fecha")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Elecciones");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Anio = 2024,
                            Fecha = new DateTime(2024, 5, 19, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsActive = true,
                            Tipo = "Presidenciales y Congresuales"
                        });
                });

            modelBuilder.Entity("eVote360.Domain.Entities.PartidoPolitico", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Descripcion")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<string>("LogoPath")
                        .HasColumnType("TEXT");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Siglas")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("PartidosPoliticos");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Descripcion = "Partido político (RD)",
                            IsActive = true,
                            Nombre = "Partido Revolucionario Moderno",
                            Siglas = "PRM"
                        },
                        new
                        {
                            Id = 2,
                            Descripcion = "Partido político (RD)",
                            IsActive = true,
                            Nombre = "Partido de la Liberación Dominicana",
                            Siglas = "PLD"
                        },
                        new
                        {
                            Id = 3,
                            Descripcion = "Partido político (RD)",
                            IsActive = true,
                            Nombre = "Fuerza del Pueblo",
                            Siglas = "FP"
                        },
                        new
                        {
                            Id = 4,
                            Descripcion = "Partido político (RD)",
                            IsActive = true,
                            Nombre = "Partido Revolucionario Dominicano",
                            Siglas = "PRD"
                        });
                });

            modelBuilder.Entity("eVote360.Domain.Entities.PuestoElectivo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Descripcion")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("PuestosElectivos");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Descripcion = "Puesto electivo nacional",
                            IsActive = true,
                            Nombre = "Presidencia"
                        },
                        new
                        {
                            Id = 2,
                            Descripcion = "Representación provincial",
                            IsActive = true,
                            Nombre = "Senaduría"
                        },
                        new
                        {
                            Id = 3,
                            Descripcion = "Cámara de Diputados",
                            IsActive = true,
                            Nombre = "Diputación"
                        },
                        new
                        {
                            Id = 4,
                            Descripcion = "Gobierno municipal",
                            IsActive = true,
                            Nombre = "Alcaldía"
                        },
                        new
                        {
                            Id = 5,
                            Descripcion = "Puesto nacional (acompaña candidatura presidencial)",
                            IsActive = true,
                            Nombre = "Vicepresidencia"
                        },
                        new
                        {
                            Id = 6,
                            Descripcion = "Puesto municipal (acompaña candidatura a alcaldía)",
                            IsActive = true,
                            Nombre = "Vicealcaldía"
                        },
                        new
                        {
                            Id = 7,
                            Descripcion = "Concejo municipal (regidores/as)",
                            IsActive = true,
                            Nombre = "Regiduría"
                        },
                        new
                        {
                            Id = 8,
                            Descripcion = "Director/a de Distrito Municipal",
                            IsActive = true,
                            Nombre = "Dirección Distrito Municipal"
                        },
                        new
                        {
                            Id = 9,
                            Descripcion = "Subdirector/a de Distrito Municipal",
                            IsActive = true,
                            Nombre = "Subdirección Distrito Municipal"
                        },
                        new
                        {
                            Id = 10,
                            Descripcion = "Vocales del Distrito Municipal",
                            IsActive = true,
                            Nombre = "Vocalía Distrito Municipal"
                        },
                        new
                        {
                            Id = 11,
                            Descripcion = "Representación ante el Parlamento Centroamericano (PARLACEN)",
                            IsActive = true,
                            Nombre = "Diputación PARLACEN"
                        });
                });

            modelBuilder.Entity("eVote360.Domain.Entities.Voto", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("CandidaturaId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("EleccionId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("FechaHora")
                        .HasColumnType("TEXT");

                    b.Property<int>("PuestoElectivoId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("TokenVoto")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("CandidaturaId");

                    b.HasIndex("PuestoElectivoId");

                    b.HasIndex("EleccionId", "PuestoElectivoId");

                    b.ToTable("Votos");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("eVote360.Domain.Entities.AppUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("eVote360.Domain.Entities.AppUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("eVote360.Domain.Entities.AppUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("eVote360.Domain.Entities.AppUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("eVote360.Domain.Entities.Candidatura", b =>
                {
                    b.HasOne("eVote360.Domain.Entities.Eleccion", "Eleccion")
                        .WithMany("Candidaturas")
                        .HasForeignKey("EleccionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("eVote360.Domain.Entities.PartidoPolitico", "PartidoPolitico")
                        .WithMany()
                        .HasForeignKey("PartidoPoliticoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("eVote360.Domain.Entities.PuestoElectivo", "PuestoElectivo")
                        .WithMany()
                        .HasForeignKey("PuestoElectivoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Eleccion");

                    b.Navigation("PartidoPolitico");

                    b.Navigation("PuestoElectivo");
                });

            modelBuilder.Entity("eVote360.Domain.Entities.Voto", b =>
                {
                    b.HasOne("eVote360.Domain.Entities.Candidatura", "Candidatura")
                        .WithMany("Votos")
                        .HasForeignKey("CandidaturaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("eVote360.Domain.Entities.Eleccion", "Eleccion")
                        .WithMany("Votos")
                        .HasForeignKey("EleccionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("eVote360.Domain.Entities.PuestoElectivo", "PuestoElectivo")
                        .WithMany()
                        .HasForeignKey("PuestoElectivoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Candidatura");

                    b.Navigation("Eleccion");

                    b.Navigation("PuestoElectivo");
                });

            modelBuilder.Entity("eVote360.Domain.Entities.Candidatura", b =>
                {
                    b.Navigation("Votos");
                });

            modelBuilder.Entity("eVote360.Domain.Entities.Eleccion", b =>
                {
                    b.Navigation("Candidaturas");

                    b.Navigation("Votos");
                });
#pragma warning restore 612, 618
        }
    }
}
