// <auto-generated />
using System;
using FutureVest.Data.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace FutureVest.Data.Persistence.Migrations
{
    [DbContext(typeof(FutureVestDbContext))]
    [Migration("20260114141607_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.0");

            modelBuilder.Entity("FutureVest.Data.Entities.Country", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsEligible")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Iso3")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("Region")
                        .HasMaxLength(80)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Iso3")
                        .IsUnique();

                    b.ToTable("Countries");
                });

            modelBuilder.Entity("FutureVest.Data.Entities.CountryIndicator", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("CountryId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("MacroIndicatorId")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Missing")
                        .HasColumnType("INTEGER");

                    b.Property<double?>("Value")
                        .HasColumnType("REAL");

                    b.Property<int>("Year")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("MacroIndicatorId");

                    b.HasIndex("CountryId", "MacroIndicatorId", "Year")
                        .IsUnique();

                    b.ToTable("CountryIndicators");
                });

            modelBuilder.Entity("FutureVest.Data.Entities.MacroIndicator", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("TEXT");

                    b.Property<bool>("HigherIsBetter")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("TEXT");

                    b.Property<string>("Unit")
                        .HasMaxLength(40)
                        .HasColumnType("TEXT");

                    b.Property<double>("Weight")
                        .HasColumnType("REAL");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.ToTable("MacroIndicators");
                });

            modelBuilder.Entity("FutureVest.Data.Entities.CountryIndicator", b =>
                {
                    b.HasOne("FutureVest.Data.Entities.Country", "Country")
                        .WithMany("Indicators")
                        .HasForeignKey("CountryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FutureVest.Data.Entities.MacroIndicator", "MacroIndicator")
                        .WithMany("CountryIndicators")
                        .HasForeignKey("MacroIndicatorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Country");

                    b.Navigation("MacroIndicator");
                });

            modelBuilder.Entity("FutureVest.Data.Entities.Country", b =>
                {
                    b.Navigation("Indicators");
                });

            modelBuilder.Entity("FutureVest.Data.Entities.MacroIndicator", b =>
                {
                    b.Navigation("CountryIndicators");
                });
#pragma warning restore 612, 618
        }
    }
}
